@startuml
'https://plantuml.com/sequence-diagram

autonumber

Login -> Front:  Lesson request
Front --> Back: Lesson request
Back-->DB: Request questions
DB-->Back: Send questions
Back-->Front: Generate lesson
Front-->Login: Begin lesson

Login->Front: Send answer
Front->Back: Request answer check
Back->DB: Check answer
DB->Back: Send response
Back->Front: Send response
Front->Login: Send responsee

@enduml